// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ads/AdsSystem.tsx": () => import("../components/mockups/ads/AdsSystem.tsx"),
  "./components/mockups/ads/StaffAds.tsx": () => import("../components/mockups/ads/StaffAds.tsx")
};
